[R5U-2431] Addresses customers inputing strings of numbers with leading whitespace
zendesk/stronger_parameters pull request #84
Opened 2021-11-02 23:36 UTC by AlisonAcuna

The Rails Upgrade Team has identified customers submitting strings of numbers with leading space to various endpoints.  This sets us up to allow for the leading whitespace.  

Example:
Invalid parameter {:key=>"ticket.requester_id", :value=>" 1901886919004", :message=>"must be an integer"} ~[link to logs](https://zendesk.datadoghq.com/logs?cols=&context_event=AQAAAXzi-QdrgHMdSAAAAABBWHppLVQ3cEFBQm9JYjM2MnJwc3JnRVc&event=&from_ts=1635895258159&index=&live=false&messageDisplay=inline&query=host%3Ai-0fc5431ca8633c0e9+service%3Aclassic+container_id%3Ad31e5c92a8a7cba1d33da61cb89b83dd18af219a53535502144bef331eebca1a&saved_view&stream_sort=desc&to_event=AQAAAXzi-RAEIwhyogAAAABBWHppLVQzeUFBQklsQjBzaXpvTjhnRS0&to_ts=1635895545860&viz=)

2021-11-02 23:40 UTC, grosser requested changes
- prefer a new class if we want to support funky edge-cases
- could possibly also just use a regex for these cases

2021-11-02 23:45 UTC, zenspider requested changes

2021-11-02 23:45 UTC, zenspider commented on lib/stronger_parameters/constraints/integer_constraint.rb
> +      elsif v.is_a?(String) && v =~ /\A-?(\d+|\s+)\d+\Z/
This should probably be `/\A\s*-?\d+\Z/` to simply allow for leading whitespace. `"  -42".to_i # => -42`

The alternative is to call `.strip` on v (including on the return line below).

2021-11-02 23:49 UTC, zenspider commented
> * prefer a new class if we want to support funky edge-cases
> * could possibly also just use a regex for these cases

This isn't a funky edge case:

```ruby
"        -42".to_i # => -42
```

And these are actually being sent in by real users. 

Why should this be a separate class when this is literally just supporting what `String.to_i` does normally?

2021-11-03 20:55 UTC, zenspider approved these changes
Better. Thank you.

2021-11-03 21:46 UTC, grosser approved these changes
still not a fan of declaring "   1" a number, but if there is a good usecase for it then 🤷

2021-11-03 22:37 UTC, merged

2021-11-03 22:37 UTC, AlisonAcuna commented
Thanks @zenspider and @grosser :)